name: Check the license of the tables

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tables/*'

  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  check-licenses:
    name: Check the license of the tables

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y licensecheck
    - name: Check licenses
      # we check all tables for a license header. If any of the
      # licenses is not LGPL-2.1+ or LGPL-3+ we flag a problem
      run: |
        test -z "$(licensecheck --check='\.(ctb|utb|cti|uti|dis)' --deb-fmt --machine tables/* | grep -Ev '(LGPL-2.1+|LGPL-3+)' | tee unknown_licenses.txt)"
    - name: Store the list of files with unknown licenses
      if: ${{ failure() }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: unknown_licenses.txt
        path: unknown_licenses.txt

