name: Check the license of the tables

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tables/*'

  pull_request:
    branches: [ master ]

jobs:
  check-licenses:
    name: Check the license of the tables

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y licensecheck
    - name: Check licenses
      # we check all tables for a license header. If any of the
      # licenses is not LGPL-2.1+ or LGPL-3+ we flag a problem
      run: |
        test -z "$(licensecheck --check='\.(ctb|utb|cti|uti|dis)' --deb-fmt --machine tables/* | grep -Ev '(LGPL-2.1+|LGPL-3+)' | tee unknown_licenses.txt)"
    - name: Store the list of files with unknown licenses
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: unknown_licenses.txt
        path: unknown_licenses.txt

