name: Make check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README
      - NEWS
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Build with ${{ matrix.ucs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # do not compile for ucs4 if ucs2 fails
      matrix:
        ucs: [ucs2, ucs4]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure
      if: matrix.ucs == 'ucs2'
    - name: Configure with ucs4
      run: ./configure --enable-ucs4
      if: matrix.ucs == 'ucs4'
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: test-suite-${{ matrix.ucs }}.log
        path: tests/test-suite.log
