name: Make check/distcheck

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README
      - NEWS
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Build with ${{ matrix.ucs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # do not compile for ucs4 if ucs2 fails
      matrix:
        ucs: [ucs2, ucs4]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure
      if: matrix.ucs == 'ucs2'
    - name: Configure with ucs4
      run: ./configure --enable-ucs4
      if: matrix.ucs == 'ucs4'
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: test-suite-${{ matrix.ucs }}.log
        path: tests/test-suite.log
    - name: Make distcheck
      run: make distcheck
