name: Run the metadata test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tables/*'
      - 'liblouis/metadata.c'
      - 'extra/generate-display-names/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'tables/*'
      - 'liblouis/metadata.c'
      - 'extra/generate-display-names/*'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  metadata-test:
    name: Build and check the metadta

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive golang-1.23
    - name: autogen && configure
      run: |
        ./autogen.sh
        ./configure --enable-ucs4
    - name: Build
      run: make
    - name: Run the metadata test
      run: make -C extra/generate-display-names
    - name: Store the log
      if: ${{ failure() }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: generate-display-names.log
        path: extra/generate-display-names/generate.log
