name: Run the metadata test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tables/*'
      - 'liblouis/metadata.c'
      - 'extra/generate-display-names/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'tables/*'
      - 'liblouis/metadata.c'
      - 'extra/generate-display-names/*'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  metadata-test:
    name: Build and check the metadta

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive golang
    - name: autogen && configure
      run: |
        ./autogen.sh
        ./configure --enable-ucs4
    - name: Build
      run: make
    - name: Run the metadata test
      run: make -C extra/generate-display-names
    - name: Store the log
      if: ${{ failure() }}
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: generate-display-names.log
        path: extra/generate-display-names/generate.log
