name: Run the metadata test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'tables/*'
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  metadata-test:
    name: Build and check the metadta

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive golang
    - name: autogen && configure
      run: |
        ./autogen.sh
        ./configure --enable-ucs4
    - name: Build
      run: make
    - name: Run the metadata test
      run: make -C extra/generate-display-names
    - name: Store the log
      if: ${{ failure() }}
      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
      with:
        name: generate-display-names.log
        path: extra/generate-display-names/generate.log
